const sample_data = [
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Exorcist",
    "FIELD4": "Exorcist, The",
    "YEAR": 1973,
    "SUBGENRE": "Possession",
    "FIELD7": "Creepy Kid",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Exorcist",
    "DIRECTOR": "William Friedkin",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 122,
    "COUNTRY": "USA",
    "IMDB": 80,
    "LB": 80,
    "MC": 82,
    "RT": 86,
    "AR": 87,
    "AVG": 83,
    "SCORE": 1165
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Shining",
    "FIELD4": "Shining, The",
    "YEAR": 1980,
    "SUBGENRE": "Haunted House",
    "FIELD7": "Psychological",
    "FIELD8": "King",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Stanley Kubrick",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 146,
    "COUNTRY": "USA",
    "IMDB": 84,
    "LB": 87,
    "MC": 63,
    "RT": 88,
    "AR": 93,
    "AVG": 83,
    "SCORE": 1160
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Halloween",
    "FIELD4": "Halloween",
    "YEAR": 1978,
    "SUBGENRE": "Slasher",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Halloween",
    "DIRECTOR": "John Carpenter",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 91,
    "COUNTRY": "USA",
    "IMDB": 78,
    "LB": 80,
    "MC": 81,
    "RT": 92,
    "AR": 89,
    "AVG": 84,
    "SCORE": 1085
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Alien",
    "FIELD4": "Alien",
    "YEAR": 1979,
    "SUBGENRE": "Sci-Fi",
    "FIELD7": "Body",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Alien",
    "DIRECTOR": "Ridley Scott",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 116,
    "COUNTRY": "USA",
    "IMDB": 85,
    "LB": 87,
    "MC": 83,
    "RT": 97,
    "AR": 94,
    "AVG": 89,
    "SCORE": 1083
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Psycho",
    "FIELD4": "Psycho",
    "YEAR": 1960,
    "SUBGENRE": "Slasher",
    "FIELD7": "B/W",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Psycho",
    "DIRECTOR": "Alfred Hitchcock",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 109,
    "COUNTRY": "USA",
    "IMDB": 85,
    "LB": 88,
    "MC": 97,
    "RT": 96,
    "AR": 94,
    "AVG": 92,
    "SCORE": 1064
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Texas Chain Saw Massacre",
    "FIELD4": "Texas Chain Saw Massacre, The",
    "YEAR": 1974,
    "SUBGENRE": "Backwoods",
    "FIELD7": "Slasher",
    "FIELD8": "Cannibal",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Texas Chainsaw Massacre",
    "DIRECTOR": "Tobe Hooper",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 83,
    "COUNTRY": "USA",
    "IMDB": 75,
    "LB": 79,
    "MC": 75,
    "RT": 88,
    "AR": 82,
    "AVG": 80,
    "SCORE": 1063
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Thing",
    "FIELD4": "Thing, The",
    "YEAR": 1982,
    "SUBGENRE": "Sci-Fi",
    "FIELD7": "Body",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": true,
    "FRANCHISE": "",
    "DIRECTOR": "John Carpenter",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 109,
    "COUNTRY": "USA",
    "IMDB": 82,
    "LB": 85,
    "MC": 57,
    "RT": 81,
    "AR": 92,
    "AVG": 79,
    "SCORE": 1053
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Jaws",
    "FIELD4": "Jaws",
    "YEAR": 1975,
    "SUBGENRE": "Nature",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Jaws",
    "DIRECTOR": "Steven Spielberg",
    "FIELD13": "",
    "RATED": "PG",
    "RUNTIME": 124,
    "COUNTRY": "USA",
    "IMDB": 80,
    "LB": 84,
    "MC": 87,
    "RT": 97,
    "AR": 90,
    "AVG": 88,
    "SCORE": 980
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Rosemary's Baby",
    "FIELD4": "Rosemary's Baby",
    "YEAR": 1968,
    "SUBGENRE": "Psychological",
    "FIELD7": "Occult",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Roman Polanski",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 137,
    "COUNTRY": "USA",
    "IMDB": 80,
    "LB": 83,
    "MC": 96,
    "RT": 99,
    "AR": 87,
    "AVG": 89,
    "SCORE": 979
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Night of the Living Dead",
    "FIELD4": "Night of the Living Dead",
    "YEAR": 1968,
    "SUBGENRE": "Zombie/Virus",
    "FIELD7": "B/W",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Of the Dead",
    "DIRECTOR": "George A. Romero",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 96,
    "COUNTRY": "USA",
    "IMDB": 79,
    "LB": 80,
    "MC": 89,
    "RT": 96,
    "AR": 88,
    "AVG": 86,
    "SCORE": 950
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "A Nightmare on Elm Street",
    "FIELD4": "Nightmare on Elm Street, A",
    "YEAR": 1984,
    "SUBGENRE": "Slasher",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Elm Street",
    "DIRECTOR": "Wes Craven",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 91,
    "COUNTRY": "USA",
    "IMDB": 75,
    "LB": 75,
    "MC": 76,
    "RT": 94,
    "AR": 83,
    "AVG": 81,
    "SCORE": 889
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Silence of the Lambs",
    "FIELD4": "Silence of the Lambs, The",
    "YEAR": 1991,
    "SUBGENRE": "Thriller",
    "FIELD7": "Cannibal",
    "FIELD8": "Crime",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Hannibal",
    "DIRECTOR": "Jonathan Demme",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 118,
    "COUNTRY": "USA",
    "IMDB": 86,
    "LB": 85,
    "MC": 85,
    "RT": 95,
    "AR": 95,
    "AVG": 89,
    "SCORE": 880
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Dawn of the Dead",
    "FIELD4": "Dawn of the Dead",
    "YEAR": 1978,
    "SUBGENRE": "Zombie/Virus",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": true
    },
    "R": false,
    "FRANCHISE": "Of the Dead",
    "DIRECTOR": "George A. Romero",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 127,
    "COUNTRY": "USA",
    "IMDB": 79,
    "LB": 80,
    "MC": 71,
    "RT": 93,
    "AR": 90,
    "AVG": 83,
    "SCORE": 811
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Suspiria",
    "FIELD4": "Suspiria",
    "YEAR": 1977,
    "SUBGENRE": "Occult",
    "FIELD7": "Giallo",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Dario Argento",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 92,
    "COUNTRY": "Italy",
    "IMDB": 75,
    "LB": 80,
    "MC": 79,
    "RT": 92,
    "AR": 83,
    "AVG": 82,
    "SCORE": 803
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Fly",
    "FIELD4": "Fly, The",
    "YEAR": 1986,
    "SUBGENRE": "Body",
    "FIELD7": "Sci-Fi",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": true,
    "FRANCHISE": "",
    "DIRECTOR": "David Cronenberg",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 96,
    "COUNTRY": "USA",
    "IMDB": 75,
    "LB": 79,
    "MC": 79,
    "RT": 91,
    "AR": 82,
    "AVG": 81,
    "SCORE": 795
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Nosferatu",
    "FIELD4": "Nosferatu",
    "YEAR": 1922,
    "SUBGENRE": "Vampire",
    "FIELD7": "Silent",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "F. W. Murnau",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 81,
    "COUNTRY": "Germany",
    "IMDB": 80,
    "LB": 79,
    "MC": null,
    "RT": 97,
    "AR": 87,
    "AVG": 86,
    "SCORE": 763
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Scream",
    "FIELD4": "Scream",
    "YEAR": 1996,
    "SUBGENRE": "Slasher",
    "FIELD7": "Meta",
    "FIELD8": "Comedy",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Scream",
    "DIRECTOR": "Wes Craven",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 111,
    "COUNTRY": "USA",
    "IMDB": 72,
    "LB": 73,
    "MC": 65,
    "RT": 79,
    "AR": 78,
    "AVG": 73,
    "SCORE": 763
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Evil Dead 2",
    "FIELD4": "Evil Dead 2",
    "YEAR": 1987,
    "SUBGENRE": "Demonic",
    "FIELD7": "Comedy",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": true,
    "FRANCHISE": "Evil Dead",
    "DIRECTOR": "Sam Rami",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 84,
    "COUNTRY": "USA",
    "IMDB": 78,
    "LB": 80,
    "MC": 69,
    "RT": 98,
    "AR": 89,
    "AVG": 83,
    "SCORE": 730
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Carrie",
    "FIELD4": "Carrie",
    "YEAR": 1976,
    "SUBGENRE": "Supernatural",
    "FIELD7": "King",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Brian De Palma",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 98,
    "COUNTRY": "USA",
    "IMDB": 74,
    "LB": 76,
    "MC": 85,
    "RT": 93,
    "AR": 76,
    "AVG": 81,
    "SCORE": 726
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Get Out",
    "FIELD4": "Get Out",
    "YEAR": 2017,
    "SUBGENRE": "Psychological",
    "FIELD7": "Thriller",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Jordan Peele",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 104,
    "COUNTRY": "USA",
    "IMDB": 77,
    "LB": 82,
    "MC": 84,
    "RT": 99,
    "AR": 87,
    "AVG": 86,
    "SCORE": 711
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Blair Witch Project",
    "FIELD4": "Blair Witch Project, The",
    "YEAR": 1999,
    "SUBGENRE": "Occult",
    "FIELD7": "Found Footage",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Blair Witch",
    "DIRECTOR": "Daniel Myrick",
    "FIELD13": "Eduardo Sanchez",
    "RATED": "R",
    "RUNTIME": 81,
    "COUNTRY": "USA",
    "IMDB": 64,
    "LB": 66,
    "MC": 81,
    "RT": 86,
    "AR": 55,
    "AVG": 70,
    "SCORE": 706
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "28 Days later",
    "FIELD4": "28 Days later",
    "YEAR": 2002,
    "SUBGENRE": "Zombie/Virus",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Danny Boyle",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 113,
    "COUNTRY": "United Kingdom",
    "IMDB": 76,
    "LB": 75,
    "MC": 73,
    "RT": 87,
    "AR": 85,
    "AVG": 79,
    "SCORE": 697
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "An American Werewolf in London",
    "FIELD4": "American Werewolf in London, An",
    "YEAR": 1981,
    "SUBGENRE": "Therianthropy",
    "FIELD7": "Comedy",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "John Landis",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 97,
    "COUNTRY": "USA",
    "IMDB": 76,
    "LB": 78,
    "MC": 60,
    "RT": 89,
    "AR": 85,
    "AVG": 78,
    "SCORE": 685
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Let the Right One in",
    "FIELD4": "Let the Right One in",
    "YEAR": 2008,
    "SUBGENRE": "Vampire",
    "FIELD7": "Creepy Kid",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Tomas Alfredson",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 114,
    "COUNTRY": "Sweden",
    "IMDB": 79,
    "LB": 82,
    "MC": 82,
    "RT": 98,
    "AR": 90,
    "AVG": 86,
    "SCORE": 669
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Bride of Frankenstein",
    "FIELD4": "Bride of Frankenstein",
    "YEAR": 1935,
    "SUBGENRE": "Monster",
    "FIELD7": "Sci-Fi",
    "FIELD8": "B/W",
    "S": {
      "P": true
    },
    "R": false,
    "FRANCHISE": "Universal",
    "DIRECTOR": "James Whale",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 75,
    "COUNTRY": "USA",
    "IMDB": 79,
    "LB": 81,
    "MC": null,
    "RT": 100,
    "AR": 88,
    "AVG": 87,
    "SCORE": 651
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Poltergeist",
    "FIELD4": "Poltergeist",
    "YEAR": 1982,
    "SUBGENRE": "Spirits",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Poltergeist",
    "DIRECTOR": "Tobe Hooper",
    "FIELD13": "",
    "RATED": "PG",
    "RUNTIME": 114,
    "COUNTRY": "USA",
    "IMDB": 74,
    "LB": 73,
    "MC": 79,
    "RT": 88,
    "AR": 78,
    "AVG": 78,
    "SCORE": 638
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Descent",
    "FIELD4": "Descent, The",
    "YEAR": 2005,
    "SUBGENRE": "Neo-Monster",
    "FIELD7": "Psychological",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Neil Marshall",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 99,
    "COUNTRY": "United Kingdom",
    "IMDB": 72,
    "LB": 72,
    "MC": 71,
    "RT": 85,
    "AR": 75,
    "AVG": 75,
    "SCORE": 630
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Evil Dead",
    "FIELD4": "Evil Dead, The",
    "YEAR": 1981,
    "SUBGENRE": "Demonic",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Evil Dead",
    "DIRECTOR": "Sam Rami",
    "FIELD13": "",
    "RATED": "NC-17",
    "RUNTIME": 85,
    "COUNTRY": "USA",
    "IMDB": 75,
    "LB": 75,
    "MC": 71,
    "RT": 95,
    "AR": 84,
    "AVG": 80,
    "SCORE": 630
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Omen",
    "FIELD4": "Omen, The",
    "YEAR": 1976,
    "SUBGENRE": "Demonic",
    "FIELD7": "Creepy Kid",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "The Omen",
    "DIRECTOR": "Richard Donner",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 111,
    "COUNTRY": "United Kingdom",
    "IMDB": 76,
    "LB": 72,
    "MC": 62,
    "RT": 86,
    "AR": 80,
    "AVG": 75,
    "SCORE": 588
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Wickerman",
    "FIELD4": "Wickerman, The",
    "YEAR": 1973,
    "SUBGENRE": "Fanaticism",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Robin Hardy",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 88,
    "COUNTRY": "United Kingdom",
    "IMDB": 76,
    "LB": 78,
    "MC": 87,
    "RT": 90,
    "AR": 82,
    "AVG": 83,
    "SCORE": 578
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Cabinet of Dr. Caligari",
    "FIELD4": "Cabinet of Dr. Caligari, The",
    "YEAR": 1920,
    "SUBGENRE": "Psychological",
    "FIELD7": "Silent",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Robert Wiene",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 67,
    "COUNTRY": "Germany",
    "IMDB": 81,
    "LB": 80,
    "MC": null,
    "RT": 100,
    "AR": 90,
    "AVG": 88,
    "SCORE": 575
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The VVitch",
    "FIELD4": "Witch, The",
    "YEAR": 2015,
    "SUBGENRE": "Occult",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Robert Eggers",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 92,
    "COUNTRY": "USA",
    "IMDB": 68,
    "LB": 76,
    "MC": 83,
    "RT": 91,
    "AR": 55,
    "AVG": 75,
    "SCORE": 557
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Birds",
    "FIELD4": "Birds, The",
    "YEAR": 1963,
    "SUBGENRE": "Nature",
    "FIELD7": "B/W",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Alfred Hitchcock",
    "FIELD13": "",
    "RATED": "PG-13",
    "RUNTIME": 119,
    "COUNTRY": "USA",
    "IMDB": 77,
    "LB": 76,
    "MC": 87,
    "RT": 96,
    "AR": 83,
    "AVG": 84,
    "SCORE": 553
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Hellraiser",
    "FIELD4": "Hellraiser",
    "YEAR": 1987,
    "SUBGENRE": "Demonic",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Hellraiser",
    "DIRECTOR": "Clive Barker",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 94,
    "COUNTRY": "United Kingdom",
    "IMDB": 70,
    "LB": 69,
    "MC": 57,
    "RT": 63,
    "AR": 73,
    "AVG": 66,
    "SCORE": 550
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Innocents",
    "FIELD4": "Innocents, The",
    "YEAR": 1961,
    "SUBGENRE": "Psychological",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Jack Clayton",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 100,
    "COUNTRY": "United Kingdom",
    "IMDB": 79,
    "LB": 81,
    "MC": null,
    "RT": 96,
    "AR": 86,
    "AVG": 86,
    "SCORE": 536
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Hereditary",
    "FIELD4": "Hereditary",
    "YEAR": 2018,
    "SUBGENRE": "Occult",
    "FIELD7": "Possession",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Ari Aster",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 127,
    "COUNTRY": "USA",
    "IMDB": 73,
    "LB": 79,
    "MC": 87,
    "RT": 89,
    "AR": 60,
    "AVG": 78,
    "SCORE": 527
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Cabin in the Woods",
    "FIELD4": "Cabin in the Woods, The",
    "YEAR": 2012,
    "SUBGENRE": "Comedy",
    "FIELD7": "Meta",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Drew Goddard",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 95,
    "COUNTRY": "USA",
    "IMDB": 70,
    "LB": 73,
    "MC": 72,
    "RT": 92,
    "AR": 73,
    "AVG": 76,
    "SCORE": 516
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Don't Look Now",
    "FIELD4": "Don't Look Now",
    "YEAR": 1973,
    "SUBGENRE": "Psychological",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Nicolas Roeg",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 110,
    "COUNTRY": "United Kingdom",
    "IMDB": 73,
    "LB": 77,
    "MC": null,
    "RT": 96,
    "AR": 78,
    "AVG": 81,
    "SCORE": 515
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "It Follows",
    "FIELD4": "It Follows",
    "YEAR": 2014,
    "SUBGENRE": "Supernatural",
    "FIELD7": "Psychological",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "David Robert Mitchell",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 100,
    "COUNTRY": "USA",
    "IMDB": 68,
    "LB": 74,
    "MC": 83,
    "RT": 97,
    "AR": 65,
    "AVG": 77,
    "SCORE": 514
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Freaks",
    "FIELD4": "Freaks",
    "YEAR": 1932,
    "SUBGENRE": "Thriller",
    "FIELD7": "B/W",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Tod Browning",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 64,
    "COUNTRY": "USA",
    "IMDB": 79,
    "LB": 78,
    "MC": null,
    "RT": 94,
    "AR": 88,
    "AVG": 85,
    "SCORE": 511
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Eyes Without a Face",
    "FIELD4": "Eyes Without a Face",
    "YEAR": 1960,
    "SUBGENRE": "Thriller",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Georges Franju",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 90,
    "COUNTRY": "France",
    "IMDB": 78,
    "LB": 80,
    "MC": 90,
    "RT": 98,
    "AR": 87,
    "AVG": 87,
    "SCORE": 509
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Frankenstein",
    "FIELD4": "Frankenstein",
    "YEAR": 1931,
    "SUBGENRE": "Monster",
    "FIELD7": "Sci-Fi",
    "FIELD8": "B/W",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "Universal",
    "DIRECTOR": "James Whale",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 70,
    "COUNTRY": "USA",
    "IMDB": 79,
    "LB": 78,
    "MC": null,
    "RT": 100,
    "AR": 87,
    "AVG": 86,
    "SCORE": 508
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Haunting",
    "FIELD4": "Haunting, The",
    "YEAR": 1963,
    "SUBGENRE": "Haunted House",
    "FIELD7": "B/W",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Robert Wise",
    "FIELD13": "",
    "RATED": "G",
    "RUNTIME": 112,
    "COUNTRY": "USA",
    "IMDB": 76,
    "LB": 76,
    "MC": 74,
    "RT": 86,
    "AR": 82,
    "AVG": 79,
    "SCORE": 504
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Repulsion",
    "FIELD4": "Repulsion",
    "YEAR": 1965,
    "SUBGENRE": "Psychological",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Roman Polanski",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 105,
    "COUNTRY": "United Kingdom",
    "IMDB": 78,
    "LB": 80,
    "MC": 91,
    "RT": 100,
    "AR": 87,
    "AVG": 87,
    "SCORE": 490
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "The Babadook",
    "FIELD4": "Babadook, The",
    "YEAR": 2014,
    "SUBGENRE": "Psychological",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Jennifer Kent",
    "FIELD13": "",
    "RATED": "NR",
    "RUNTIME": 94,
    "COUNTRY": "Australia",
    "IMDB": 68,
    "LB": 73,
    "MC": 86,
    "RT": 98,
    "AR": 73,
    "AVG": 80,
    "SCORE": 489
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Audition",
    "FIELD4": "Audition",
    "YEAR": 1999,
    "SUBGENRE": "Torture",
    "FIELD7": "",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Takashi Miike",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 115,
    "COUNTRY": "Japan",
    "IMDB": 72,
    "LB": 74,
    "MC": 69,
    "RT": 79,
    "AR": 80,
    "AVG": 75,
    "SCORE": 481
  },
  {
    "TRAILER": "",
    "STREAM": "",
    "TITLE": "Black Christmas",
    "FIELD4": "Black Christmas",
    "YEAR": 1974,
    "SUBGENRE": "Slasher",
    "FIELD7": "Christmas",
    "FIELD8": "",
    "S": {
      "P": false
    },
    "R": false,
    "FRANCHISE": "",
    "DIRECTOR": "Bob Clark",
    "FIELD13": "",
    "RATED": "R",
    "RUNTIME": 98,
    "COUNTRY": "Canada",
    "IMDB": 72,
    "LB": 74,
    "MC": null,
    "RT": 64,
    "AR": 76,
    "AVG": 72,
    "SCORE": 475
  }
]

module.exports = { sample_data }